name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
jobs:
  Test-Own-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: mwoodson11/act-test@v1.1
        with:
          who-to-greet: 'Mark'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"